apiVersion: batch/v1
kind: Job
metadata:
  name: vwap-loadgen
  namespace: default
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 180 # # Job and its Pods automatically deleted 180 seconds after completion.
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: loadgen
          image: gulshan1988/volt-vwap:loadgen-v2
          command: ["java"]
          args:
            - "-cp"
            - "/app/volt-vwap-fixed.jar"
            - "com.voltactivedata.vwapdemo.client.DemoUpdatedRandomTickers"
            - "$(VOLTDB_SVC_ADDR)"
            - "0"
            - "$(TOTAL_OPERATIONS)"
            - "$(TPS)"
            - "$(NUM_CLIENTS)"
            - "0"
            - "/app/tickerData"
            - "$(KAFKA_BROKER_ADDR)"
          envFrom:
            - configMapRef:
                name: vwap-loadgen-config
